fixtures:
  repositories:
    "stdlib":
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref:  "4.25.0"
    "firewall":
      repo: "git://github.com/puppetlabs/puppetlabs-firewall.git"
      ref:  ${MOD_FIREWALL}
    
  symlinks:
    "g_firewall": "#{source_dir}"
